# Generated by Django 5.2.8 on 2025-12-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=60)),
                ('Product_desc', models.TextField()),
                ('Product_price', models.IntegerField(max_length=60)),
                ('Product_cat', models.CharField(max_length=60)),
                ('Product_image', models.CharField(max_length=60)),
            ],
        ),
    ]
